# Generated by Django 5.0.1 on 2024-02-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=100)),
                ('banner_name_sub', models.CharField(blank=True, max_length=100)),
                ('banner_image', models.ImageField(upload_to='media/banner/images/')),
                ('banner_url', models.URLField(blank=True, default='#')),
                ('button_text', models.CharField(default='Buy Now', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
