# Generated by Django 5.0.1 on 2024-01-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
