# Generated by Django 5.0.1 on 2024-02-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='product_offer_image',
            field=models.ImageField(blank=True, upload_to='media/product_offer/images/'),
        ),
    ]
