# Generated by Django 5.0.1 on 2024-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0002_alter_productoffer_product_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='category_offer_image',
            field=models.ImageField(blank=True, upload_to='media/category_offer/'),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='product_offer_image',
            field=models.ImageField(blank=True, upload_to='media/product_offer/'),
        ),
    ]
