# Generated by Django 5.0.1 on 2024-02-05 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_price',
        ),
    ]
