# Generated by Django 5.0.1 on 2024-02-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderproduct_order_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
