# Generated by Django 5.0.1 on 2024-02-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_additional_discount_order_order_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
