# Generated by Django 5.0.1 on 2024-03-12 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_shipping_address'),
        ('product_management', '0005_alter_additional_product_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_management.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('SUCCESS', 'Success'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
    ]
