# Generated by Django 5.0.1 on 2024-02-15 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='total_coupons',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
