# Generated by Django 5.0.1 on 2024-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_usercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_product_image',
            name='image',
            field=models.ImageField(upload_to='media/additional_photos/'),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='thumbnail_image',
            field=models.ImageField(upload_to='media/product_variant/'),
        ),
    ]
